// Veil — Sprint 1 spike host.
//
// Proves the trivial statement "I know x such that x * x == 25" in the zkVM.
// The secret witness x is a PRIVATE input; only the public square (25) appears
// in the journal.
//
// Two modes:
//   cargo run -p host                 # STARK proof, verify locally (fast-ish)
//   cargo run -p host -- 7            # wrong witness -> proving fails (expected)
//   cargo run -p host -- groth16      # Groth16 proof (needs Docker, RISC0_DEV_MODE=0)
//                                       writes proof.txt: seal / image_id / journal_digest
//
// The Groth16 mode produces exactly the three values the Nethermind Stellar
// verifier's router `verify(seal, image_id, journal_digest)` expects.
//
// The ELF and image ID are generated by risc0-build (see methods/build.rs).
use methods::{METHOD_ELF, METHOD_ID};
use risc0_zkvm::{compute_image_id, default_prover, ExecutorEnv, ProverOpts};
use risc0_ethereum_contracts::encode_seal;
use sha2::{Digest, Sha256};

fn main() {
    // Run with `RUST_LOG=info cargo run` to see proving logs.
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let arg = std::env::args().nth(1);
    let groth16 = arg.as_deref() == Some("groth16");

    // Secret witness: x such that x * x == 25. Default 5; a numeric argv[1] overrides.
    let x: u64 = match arg.as_deref() {
        Some("groth16") | None => 5,
        Some(a) => a.parse().expect("witness must be a u64 or 'groth16'"),
    };

    println!(
        "Proving knowledge of x such that x * x == 25 (witness kept private){}...",
        if groth16 { " [Groth16]" } else { "" }
    );

    // Write x as a PRIVATE input over the executor channel (not the journal).
    let env = ExecutorEnv::builder().write(&x).unwrap().build().unwrap();

    let prover = default_prover();

    if groth16 {
        // Groth16: succinct proof verifiable on-chain. Requires Docker + RISC0_DEV_MODE=0.
        let opts = ProverOpts::groth16();
        let receipt = prover
            .prove_with_opts(env, METHOD_ELF, &opts)
            .unwrap()
            .receipt;

        // The three values the Stellar verifier router expects:
        //   seal           = encode_seal(receipt)  (Groth16 seal + routing selector prefix)
        //   image_id       = the guest program ID (32 bytes)
        //   journal_digest = sha256(journal bytes)
        let seal = encode_seal(&receipt).unwrap();
        let image_id = compute_image_id(METHOD_ELF).unwrap();
        let journal_digest: [u8; 32] = Sha256::digest(&receipt.journal.bytes).into();

        let out = format!(
            "{}\n{}\n{}\n",
            hex::encode(&seal),
            hex::encode(image_id.as_bytes()),
            hex::encode(journal_digest),
        );
        std::fs::write("proof.txt", &out).unwrap();

        // Sanity: it must still verify locally too.
        receipt.verify(METHOD_ID).unwrap();
        println!("✅ Groth16 receipt verified locally. Wrote proof.txt:");
        println!("   seal            ({} bytes)", seal.len());
        println!("   image_id        {}", hex::encode(image_id.as_bytes()));
        println!("   journal_digest  {}", hex::encode(journal_digest));
    } else {
        // STARK: fast local proof for iteration. Does not verify on-chain.
        let receipt = prover.prove(env, METHOD_ELF).unwrap().receipt;
        let square: u64 = receipt.journal.decode().unwrap();
        println!("Journal (public output): x * x = {square}");
        assert_eq!(square, 25);
        receipt.verify(METHOD_ID).unwrap();
        println!("✅ STARK receipt verified locally against image ID {METHOD_ID:?}");
    }
}
